name: CI
on: [push, pull_request]

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
        env:
          RUSTFLAGS: -D warnings
      - uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          RUSTFLAGS: -D warnings
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
        env:
          RUSTFLAGS: -D warnings
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
